version: '3.8'

services:
  db:
    image: postgres:16
    container_name: wordle_db
    restart: always
    environment:
      POSTGRES_DB: wordle_db
      POSTGRES_USER: wordle_user
      POSTGRES_PASSWORD: wordle_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: wordle_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://wordle_user:wordle_password@db:5432/wordle_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
