# Generated by Django 5.1.5 on 2025-03-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlist',
            old_name='text',
            new_name='word',
        ),
    ]
