# Generated by Django 5.1.7 on 2025-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trophy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
