# Generated by Django 5.1.7 on 2025-03-14 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_left', models.IntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_to_guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.wordlist')),
            ],
        ),
        migrations.CreateModel(
            name='WordStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_words', models.IntegerField(default=0)),
                ('words_used_today', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='WordleGame',
        ),
    ]
